# Generated by Django 4.2.7 on 2023-11-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("intensity", models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
    ]
