# Generated by Django 4.2.7 on 2023-11-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_mappoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mappoint",
            name="intensity",
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="latitude",
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name="mappoint",
            name="longitude",
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
    ]
